#!/usr/bin/env python3
"""
Assemble the LaTeX report from the artefacts produced by training and
evaluation.

Reads
  * ``<eval_dir>/metrics.json``      written by evaluation/evaluate_gfm.py
  * ``<run_dir>/train_log_*.csv``    written by utils/loss_logger.py
  * ``<run_dir>/run_config.json``    written by train.py

Writes into ``paper/generated/``
  * ``results_table.tex``   FID / IS / MMD / KID per dataset
  * ``loss_table.tex``      final and best training loss, steps, wall-clock
  * ``config_table.tex``    the configuration each run was trained with
  * ``status.tex``          a banner naming which runs are still missing

and copies the t-SNE / sample-grid figures into ``paper/figures/``.

Every table renders with ``--`` placeholders for runs whose artefacts do not
exist yet, so ``paper/main.tex`` always compiles.

Example
-------
    python scripts/build_paper.py \
        --result CIFAR-10=results/cifar10 \
        --result ImageNet=results/imagenet \
        --result ImageNet-LT=results/imagenet_lt \
        --run CIFAR-10=runs/cifar10/models \
        --run ImageNet=runs/imagenet/models \
        --run ImageNet-LT=runs/imagenet_lt/models
"""

import argparse
import csv
import json
import os
import shutil

PAPER_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "paper")
PAPER_DIR = os.path.normpath(PAPER_DIR)
GEN_DIR = os.path.join(PAPER_DIR, "generated")
FIG_DIR = os.path.join(PAPER_DIR, "figures")

MISS = "--"


def tex_escape(s):
    for a, b in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"),
                 ("$", r"\$"), ("#", r"\#"), ("_", r"\_"), ("{", r"\{"),
                 ("}", r"\}"), ("~", r"\textasciitilde{}"),
                 ("^", r"\textasciicircum{}")):
        s = str(s).replace(a, b)
    return s


def parse_pairs(specs):
    out = {}
    for spec in specs or []:
        label, _, path = spec.partition("=")
        if not path:
            label, path = os.path.basename(os.path.normpath(label)), label
        out[label] = path
    return out


def load_json(path):
    if path and os.path.exists(path):
        with open(path) as f:
            return json.load(f)
    return None


def read_csv_rows(path):
    if not os.path.exists(path) or os.path.getsize(path) == 0:
        return []
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def fmt(v, digits=2, missing=MISS):
    if v is None:
        return missing
    try:
        return f"{float(v):.{digits}f}"
    except (TypeError, ValueError):
        return missing


# --------------------------------------------------------------------------- #
#  Tables
# --------------------------------------------------------------------------- #
def build_results_table(results, path, runs=None):
    """FID and friends, plus what each row cost in wall-clock time.

    Train (h) comes from the training log and covers the whole run even
    when it was split over chained Slurm jobs; Infer (min) is the time to
    sample the N_gen images, i.e. inference only, with the metric
    computation excluded (it is in metrics.json as timing.metrics_s).
    """
    runs = runs or {}
    lines = [
        r"% auto-generated by scripts/build_paper.py -- do not edit",
        r"\begin{tabular}{l r r r r r r r r}",
        r"\toprule",
        r"Dataset & $N_{\text{gen}}$ & Res. & FID $\downarrow$ & "
        r"IS $\uparrow$ & MMD $\downarrow$ & KID $\downarrow$ & "
        r"Train (h) & Infer (min) \\",
        r"\midrule",
    ]
    for label, m in results.items():
        train_h = (runs.get(label) or {}).get("wall_hours")
        if m is None:
            lines.append(rf"{tex_escape(label)} & {MISS} & {MISS} & {MISS} & "
                         rf"{MISS} & {MISS} & {MISS} & "
                         rf"{fmt(train_h, 1)} & {MISS} \\")
            continue
        mmd = m.get("mmd") or {}
        kid = m.get("kid") or {}
        is_s = m.get("inception_score_std")
        is_txt = fmt(m.get("inception_score"), 2)
        if is_s is not None and is_txt != MISS:
            is_txt = rf"{is_txt} $\pm$ {fmt(is_s, 2)}"
        kid_txt = fmt(kid.get("kid"), 4) if kid else MISS
        # Reused samples carry no sampling time of their own, so the cell
        # stays '--' rather than claiming inference was instantaneous.
        samp_s = (m.get("timing") or {}).get("sampling_s")
        infer_min = None if samp_s is None else float(samp_s) / 60.0
        lines.append(
            rf"{tex_escape(label)} & {m.get('num_samples', MISS)} & "
            rf"{m.get('eval_image_size', MISS)} & {fmt(m.get('fid'), 2)} & "
            rf"{is_txt} & {fmt(mmd.get('mmd'), 4) if mmd else MISS} & "
            rf"{kid_txt} & {fmt(train_h, 1)} & {fmt(infer_min, 1)} \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(path, "\n".join(lines))


def build_reference_table(results, path):
    """Inception Score of the *real* reference set -- the practical upper bound."""
    lines = [
        r"% auto-generated by scripts/build_paper.py -- do not edit",
        r"\begin{tabular}{l r r r}",
        r"\toprule",
        r"Dataset & $N_{\text{real}}$ & IS (real) & IS (GFM) \\",
        r"\midrule",
    ]
    for label, m in results.items():
        if m is None:
            lines.append(rf"{tex_escape(label)} & {MISS} & {MISS} & {MISS} \\")
            continue
        lines.append(
            rf"{tex_escape(label)} & {m.get('num_reference_images', MISS)} & "
            rf"{fmt(m.get('inception_score_real'), 2)} & "
            rf"{fmt(m.get('inception_score'), 2)} \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(path, "\n".join(lines))


def summarise_run(run_dir):
    ep = read_csv_rows(os.path.join(run_dir, "train_log_epochs.csv"))
    st = read_csv_rows(os.path.join(run_dir, "train_log_steps.csv"))
    fd = read_csv_rows(os.path.join(run_dir, "train_log_fid.csv"))
    if not ep and not st:
        return None

    def col(rows, key):
        vals = []
        for r in rows:
            try:
                vals.append(float(r[key]))
            except (KeyError, TypeError, ValueError):
                pass
        return vals

    losses = col(ep, "avg_loss")
    steps = col(st, "step")
    fids = col(fd, "fid")
    # wall_time_s is cumulative across resumes (see utils/loss_logger.py),
    # so the largest value is the whole run's training time even when it
    # ran as 20+ chained jobs. Queue time between links is not counted.
    wall = col(ep, "wall_time_s") or col(st, "wall_time_s")
    return {
        "epochs": len(ep),
        "steps": int(max(steps)) if steps else None,
        "final_loss": losses[-1] if losses else None,
        "best_loss": min(losses) if losses else None,
        "best_fid": min(fids) if fids else None,
        "wall_hours": (max(wall) / 3600.0) if wall else None,
    }


def build_loss_table(runs, path):
    lines = [
        r"% auto-generated by scripts/build_paper.py -- do not edit",
        r"\begin{tabular}{l r r r r r}",
        r"\toprule",
        r"Dataset & Epochs & Steps & Final loss & Best loss & Train (h) \\",
        r"\midrule",
    ]
    for label, s in runs.items():
        if s is None:
            lines.append(rf"{tex_escape(label)} & {MISS} & {MISS} & {MISS} & "
                         rf"{MISS} & {MISS} \\")
            continue
        lines.append(
            rf"{tex_escape(label)} & {s['epochs'] or MISS} & "
            rf"{s['steps'] if s['steps'] is not None else MISS} & "
            rf"{fmt(s['final_loss'], 4)} & {fmt(s['best_loss'], 4)} & "
            rf"{fmt(s['wall_hours'], 1)} \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(path, "\n".join(lines))


CONFIG_KEYS = [
    ("image_size", "Image size"),
    ("latent_size", "Latent grid"),
    ("base_model", "Reaction net"),
    ("diffusion_network", "Correction net"),
    ("adj_mode", "Adjacency"),
    ("flow_model_type", "Coupling"),
    ("train_batch_size", "Batch"),
    ("lr", "LR"),
    ("int_method", "Solver"),
    ("nsteps", "NFE steps"),
]


def build_config_table(configs, path):
    labels = list(configs.keys())
    cols = "l" + "c" * len(labels)
    lines = [
        r"% auto-generated by scripts/build_paper.py -- do not edit",
        rf"\begin{{tabular}}{{{cols}}}",
        r"\toprule",
        "Setting & " + " & ".join(tex_escape(l) for l in labels) + r" \\",
        r"\midrule",
    ]
    for key, pretty in CONFIG_KEYS:
        cells = []
        for l in labels:
            cfg = configs[l]
            cells.append(MISS if not cfg else tex_escape(cfg.get(key, MISS)))
        lines.append(f"{pretty} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    write(path, "\n".join(lines))


def build_status(results, runs, path):
    missing_r = [l for l, m in results.items() if m is None]
    missing_t = [l for l, s in runs.items() if s is None]
    if not missing_r and not missing_t:
        write(path, "% all artefacts present\n")
        return
    parts = []
    if missing_t:
        parts.append("training logs for " + ", ".join(tex_escape(m) for m in missing_t))
    if missing_r:
        parts.append("evaluation results for " + ", ".join(tex_escape(m) for m in missing_r))
    body = ("This draft was compiled before all runs finished: "
            + "; ".join(parts) + " are not yet available, and the corresponding "
            "table entries read ``--''. Re-running "
            r"\texttt{scripts/build\_paper.py} after the runs complete fills "
            "them in automatically.")
    write(path, "\\begin{tcolorbox}[colback=yellow!8!white,colframe=yellow!55!black,"
                "boxrule=0.4pt,left=4pt,right=4pt,top=3pt,bottom=3pt]\n"
                "\\footnotesize " + body + "\n\\end{tcolorbox}\n")


def print_summary(labels, results, runs):
    """The same numbers as results_table.tex, for the job log.

    The report job is usually the only place all three datasets are seen
    together, and reading them out of the .tex is no fun.
    """
    head = (f"{'run':<16}{'FID':>9}{'IS':>9}{'epochs':>8}"
            f"{'train h':>10}{'infer min':>11}{'eval h':>9}")
    print("\n" + head)
    print("-" * len(head))
    for l in labels:
        m = results.get(l) or {}
        r = runs.get(l) or {}
        t = m.get("timing") or {}
        samp = t.get("sampling_s")
        tot = t.get("total_s")
        print(f"{l[:15]:<16}"
              f"{fmt(m.get('fid'), 2):>9}"
              f"{fmt(m.get('inception_score'), 2):>9}"
              f"{(r.get('epochs') if r.get('epochs') else MISS):>8}"
              f"{fmt(r.get('wall_hours'), 2):>10}"
              f"{fmt(None if samp is None else samp / 60.0, 1):>11}"
              f"{fmt(None if tot is None else tot / 3600.0, 2):>9}")


def write(path, text):
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text.rstrip() + "\n")
    print(f"[tex] {path}")


# --------------------------------------------------------------------------- #
#  Figures
# --------------------------------------------------------------------------- #
def copy_figures(results_dirs, results):
    os.makedirs(FIG_DIR, exist_ok=True)
    copied = []
    for label, d in results_dirs.items():
        slug = label.lower().replace(" ", "_").replace("-", "_")
        m = results.get(label) or {}
        candidates = [
            (m.get("tsne_figure"), f"tsne_{slug}"),
            (m.get("tsne_byclass_figure"), f"tsne_{slug}_byclass"),
            (m.get("sample_grid"), f"samples_{slug}"),
        ]
        for src, stem in candidates:
            if not src:
                continue
            for ext in (".pdf", ".png"):
                cand = os.path.splitext(src)[0] + ext
                if os.path.exists(cand):
                    dst = os.path.join(FIG_DIR, stem + ext)
                    shutil.copyfile(cand, dst)
                    copied.append(dst)
                    break
    for c in copied:
        print(f"[fig] {c}")
    return copied


def main(argv=None):
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--result", action="append", metavar="LABEL=DIR",
                   help="Directory containing metrics.json")
    p.add_argument("--run", action="append", metavar="LABEL=DIR",
                   help="Directory containing train_log_*.csv and run_config.json")
    p.add_argument("--gen_dir", default=GEN_DIR)
    args = p.parse_args(argv)

    result_dirs = parse_pairs(args.result)
    run_dirs = parse_pairs(args.run)
    labels = list(dict.fromkeys(list(result_dirs) + list(run_dirs)))
    if not labels:
        p.error("pass at least one --result or --run")

    results = {l: load_json(os.path.join(result_dirs[l], "metrics.json"))
               if l in result_dirs else None for l in labels}
    runs = {l: summarise_run(run_dirs[l]) if l in run_dirs else None
            for l in labels}
    configs = {l: load_json(os.path.join(run_dirs[l], "run_config.json"))
               if l in run_dirs else None for l in labels}

    for l in labels:
        print(f"[run] {l}: metrics={'yes' if results[l] else 'MISSING'}, "
              f"train-log={'yes' if runs[l] else 'MISSING'}")

    build_results_table(results, os.path.join(args.gen_dir, "results_table.tex"),
                        runs=runs)
    build_reference_table(results, os.path.join(args.gen_dir, "reference_table.tex"))
    build_loss_table(runs, os.path.join(args.gen_dir, "loss_table.tex"))
    build_config_table(configs, os.path.join(args.gen_dir, "config_table.tex"))
    build_status(results, runs, os.path.join(args.gen_dir, "status.tex"))
    copy_figures(result_dirs, results)
    print_summary(labels, results, runs)
    print("\n[done] now build the PDF:  cd paper && latexmk -pdf main.tex")


if __name__ == "__main__":
    main()
